# Generated by Django 4.2.2 on 2023-06-29 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='date_liked',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 20, 27, 25, 463127)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 20, 27, 25, 462872)),
        ),
    ]
