# Generated by Django 4.2.2 on 2023-06-29 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_like_date_liked_alter_post_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='date_liked',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 20, 28, 21, 150309)),
        ),
    ]
